FROM eclipse-temurin:17-jdk

# Set the working directory inside the container
WORKDIR /app

# Install Maven
RUN apt-get update && \
    apt-get install -y maven && \
    rm -rf /var/lib/apt/lists/*

# Copy all project files into the container
COPY . .

# Build the project using Maven
RUN mvn clean package

# Run the jar file generated by Maven
CMD ["java", "-jar", "target/Java_Junit_Assignment-1.0-SNAPSHOT.jar"]
